# Generated by Django 3.2.9 on 2021-11-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(default='birinchi', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newsindex',
            name='slug',
            field=models.SlugField(default='ikkinchi', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
