# Generated by Django 3.2.9 on 2021-11-04 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211104_1557'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsindex',
        ),
    ]
