# Generated by Django 3.2.9 on 2021-11-04 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_newsindex'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Yangiliklar', 'verbose_name_plural': 'Yangiliklar'},
        ),
    ]
