# Generated by Django 3.2.9 on 2021-11-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_news_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Sarlavha')),
                ('link', models.CharField(max_length=100, verbose_name='Link')),
            ],
            options={
                'verbose_name': 'Pastki Sahifalar',
                'verbose_name_plural': 'Pastki Sahifalar',
            },
        ),
        migrations.AlterField(
            model_name='news',
            name='obshi_description',
            field=models.TextField(blank=True, max_length=3001, verbose_name='Hamma Tekst'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.TextField(max_length=351, verbose_name='Sarlavhasi'),
        ),
    ]
