# Generated by Django 3.2.9 on 2021-11-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20211105_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='link',
            field=models.CharField(blank=True, max_length=100, verbose_name='Link'),
        ),
    ]
