# Generated by Django 3.2.9 on 2021-11-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_pages_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': "Pastki Bog'lanish",
                'verbose_name_plural': "Pastki Bog'lanish",
            },
        ),
    ]
