# Generated by Django 3.2.9 on 2021-11-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_contactfooter'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name': 'Biz haqimizda (Asosiy menyu)',
                'verbose_name_plural': 'Biz haqimizda (Asosiy menyu)',
            },
        ),
    ]
