# Generated by Django 3.2.9 on 2021-11-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_aboutindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=500)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('telegram', models.CharField(blank=True, max_length=100)),
                ('whatsapp', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Biz haqimizda (Footer)',
                'verbose_name_plural': 'Biz haqimizda (Footer)',
            },
        ),
    ]
