# Generated by Django 3.2.9 on 2021-11-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_aboutfooter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactAboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('address', models.TextField(max_length=400)),
            ],
            options={
                'verbose_name': 'Aloqa malumotlari',
                'verbose_name_plural': 'Aloqa malumotlari',
            },
        ),
    ]
